// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdUJJT2O8GYJyqEALVQpZ4Wx13Z5PGqo',
    appId: '1:1016095914994:web:ccebe410ceb4ba3aaf896b',
    messagingSenderId: '1016095914994',
    projectId: 'co-pet-d36b9',
    authDomain: 'co-pet-d36b9.firebaseapp.com',
    storageBucket: 'co-pet-d36b9.appspot.com',
    measurementId: 'G-PGFNSLE6Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaVuaAiwcEQi0UnA_WTk580fNIa-Ve_E',
    appId: '1:1016095914994:android:ea94a34ce011ab4aaf896b',
    messagingSenderId: '1016095914994',
    projectId: 'co-pet-d36b9',
    storageBucket: 'co-pet-d36b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjGR3m9QdNCn2hnwIjgBNhE2jZld0H_yg',
    appId: '1:1016095914994:ios:647b0a7f07495d15af896b',
    messagingSenderId: '1016095914994',
    projectId: 'co-pet-d36b9',
    storageBucket: 'co-pet-d36b9.appspot.com',
    iosBundleId: 'com.example.coPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjGR3m9QdNCn2hnwIjgBNhE2jZld0H_yg',
    appId: '1:1016095914994:ios:150ae82ad1dea29faf896b',
    messagingSenderId: '1016095914994',
    projectId: 'co-pet-d36b9',
    storageBucket: 'co-pet-d36b9.appspot.com',
    iosBundleId: 'com.example.coPet.RunnerTests',
  );
}
